# Enable debug info in console
debug-mode: false

# Enable colors in console output
color-logs: true

# Language file (for translations)
language-file: lang-en.yml

# The egg totem to be held
egg-totem:
  material: TOTEM
  data: 0
  name: "&6&oEgg Totem"
  lore:
  - "&7&oKill an entity while holding this"
  - "&7&oto drop it's spawn egg on death."
  nbt: '{ench:[{id:34,lvl:10}]}'
