name: "${project.name}"
main: "${project.groupId}.${project.artifactId}.${project.name}"
version: "${project.version}"
description: "${project.name} Purpur Plugin"
author: "BillyGalbreath"
api-version: "1.13"

commands:
  eggdrop:
    description: Manage plugin
    permission: command.eggdrop
    usage: /<command> (reload | givetotem)
    aliases:
      - eggdrops
      - edrop
      - ed

permissions:
  command.eggdrop:
    description: Allows managing plugin
    default: op
